version: '2.2'
services:
  spa-2:
    build:
      # use the mono-repo root dockerfile
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - '3001:3001'
