version: '3'

services:
  multi-app:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../spa1/build:/etc/nginx/html/spa1
      - ../spa2/build:/etc/nginx/html/spa2
    #   - ../../packages/contacts-ui/build:/etc/nginx/html/contacts
    #   - ./env.json:/etc/nginx/html/env.json
    # environment:
    #   - GRAPHQL_PATH=http://local.whispirdev.com:4000/sparx-graphql-api
    #   - AUTH_API=http://local.whispirdev.com:4000/user-management-api

    ports:
      - "8080:8080"
    # restart: always
    # depends_on:
    #   - spa-2
    #   - spa-1
    #   - auth-api
  # spa-2:
  #   build:
  #     # use the mono-repo root dockerfile
  #     context: ./spa2/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./spa2/:/usr/src/app/
  #   ports:
  #     - '3001:3001'
  # spa-1:
  #   build:
  #     # use the mono-repo root dockerfile
  #     context: ./spa1/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./spa1/:/usr/src/app/
  #   ports:
  #     - '3000:3000'
  # auth-api:
  #   build:
  #     # use the mono-repo root dockerfile
  #     context: ./auth-api/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./auth-api/:/usr/src/app/
  #   ports:
  #     - '3060:3060'

  # # sparx-graphql-api:
  #   image: node:10-alpine
  #   volumes:
  #     - ../../node_modules:/usr/app/node_modules
  #     - ../../packages/sparx-graphql-api:/usr/app/packages
  #   environment:
  #     - HTTPS=true
  #   ports:
  #     - "4000:4000"

  # user-management-api:
  #   image: node:10-alpine
  #   volumes:
  #     - ../../node_modules:/usr/app/node_modules
  #     - ../../packages/user-management-api:/usr/app/packages
  #   ports:
  #     - "4001:4000"


